### ISSUE TITLE
Duplicated references

### ISSUE THREAD

**Issue by acarl005** [w201rdada/portfolio-acarl005#9]
I added the following options in the YAML front matter:

```yaml
bibliography: bibliography.bib
link-citations: true
```

[This page](https://w201rdada.github.io/portfolio-acarl005/drug-rules.html) for my first big idea showed the references at the bottom correctly.
However, for some reason my list of references is getting duplicated on [the page for my second idea](https://w201rdada.github.io/portfolio-acarl005/morgan-freeman-assistant.html).
I can't find any differences that would lead to this behavior.
Any insight?

**Comment by brooksambrose** [comment]
Should be fixed by #10

**Comment by acarl005** [comment]
@brooksambrose Merged, rebuilt and redeployed.

Now it isn't duplicating the references, but the `references.Rmd` is blank, even though it's the last page of the book. I can't find any hints in the Bookdown docs. Is there something wrong with my config?

**Comment by brooksambrose** [comment]
First you don’t appear to have run `git pull...` to fast forward your repo, so your `_build.sh` is out of date. Try updating the repo as explained in the prompt and try rebuilding the site. Your citations should appear in the righ spot. If they still don’t look right, try adding `bibliography-style: "apalike"` to `_output.yml`.

**Comment by acarl005** [comment]
Yeah I had forgotten to pull from the base fork. After doing that, building, and deploying, it worked and it looks great! Thank you @brooksambrose.
